# Les POST
POST http://localhost:3000/addcompte HTTP/1.1
Content-Type: application/json

{
    "name": "Luna",
    "email": "kerian.delourmel@gmail.com",
    "mdp": "kerian"
}

POST http://localhost:3000/addPost HTTP/1.1
Content-Type: application/json

{
    "id_compte": "e1870f9d-0ac6-4e0b-a7c5-c46c4a6c2c45"
}

POST http://localhost:3000/addLike/ab68b806-29ca-4085-b954-799d7c74bdc3 HTTP/1.1
Content-Type: application/json

{
    "id_compte": "e1870f9d-0ac6-4e0b-a7c5-c46c4a6c2c45"
}

POST http://localhost:3000/addCommentaire HTTP/1.1
Content-Type: application/json

{
    "id_compte": "75ae3a9d-95e9-4dcd-9226-f19bb54a1b6b",
    "id_post": "819d8b1b-3ce2-4b4b-8bc3-93df6b7f60fc",
    "commentaire": "J'aime le chocolat"
}

# Les GET
GET http://localhost:3000/allPost HTTP/1.1

GET http://localhost:3000/count_Like/ab68b806-29ca-4085-b954-799d7c74bdc3 HTTP/1.1

# Le DELETE
DELETE http://localhost:3000/deletelike/119e6f5a-3458-4150-aa58-22a4ed9d634a HTTP/1.1